services:
  pgadmin:
    image: dpage/pgadmin4:8.12
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@sudoku.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "80:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: sudokudb
      POSTGRES_USER: sudoku
      POSTGRES_PASSWORD: sudokupassword
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data

volumes:
  pg:
  pgadmin:
